### ISSUE TITLE
Possible incorrect main file inclusion

### ISSUE THREAD

**Issue by hunterInt** [utropicmedia/storj-nodejs#1]
I don't understand why the `main` ([here](https://github.com/utropicmedia/storj-nodejs/blob/219ac6cb3380ba519b586f3fe005c85647e40573/package.json#L5)) is the example file:
```
  "main": "HelloStorj.js",
```
Maybe this is incorrect? 

When I update your package.json's main to point to your `libUplinkNode.js` file and include it I get this error: 
```
unexpected fault address 0x800d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x800d pc=0x7fa6eb1abf0e]

goroutine 17 [running, locked to thread]:
runtime.throw(0x7fa6eb77c11a, 0x5)
	/usr/lib/go-1.12/src/runtime/panic.go:617 +0x74 fp=0xc000078c90 sp=0xc000078c60 pc=0x7fa6eb1d6a54
runtime.sigpanic()
	/usr/lib/go-1.12/src/runtime/signal_unix.go:397 +0x405 fp=0xc000078cc0 sp=0xc000078c90 pc=0x7fa6eb1eb0f5
indexbytebody(0x800d, 0xff3, 0x0, 0x70, 0xff3, 0x0, 0x800d, 0x800d, 0xff3, 0xc000078d68, ...)
	/usr/lib/go-1.12/src/internal/bytealg/indexbyte_amd64.s:124 +0xce fp=0xc000078cc8 sp=0xc000078cc0 pc=0x7fa6eb1abf0e
runtime.findnull(0x800d, 0x0)
	/usr/lib/go-1.12/src/runtime/string.go:448 +0x87 fp=0xc000078d20 sp=0xc000078cc8 pc=0x7fa6eb1f0b77
runtime.gostring(0x800d, 0x0, 0x0)
	/usr/lib/go-1.12/src/runtime/string.go:314 +0x31 fp=0xc000078d78 sp=0xc000078d20 pc=0x7fa6eb1f0821
main._Cfunc_GoString(...)
	_cgo_gotypes.go:302
main.new_uplink(0x1, 0x0, 0x0, 0x0, 0x0, 0x800d, 0xf13b70, 0xe87930, 0x0)
	/home/hunter/go/src/storj.io/storj/lib/uplinkc/uplink.go:48 +0x132 fp=0xc000078df8 sp=0xc000078d78 pc=0x7fa6eb775e72
main._cgoexpwrap_7b24c107a305_new_uplink(0x1, 0x0, 0x0, 0x0, 0x0, 0x800d, 0xf13b70, 0xe87930, 0x0)
	_cgo_gotypes.go:999 +0x5b fp=0xc000078e50 sp=0xc000078df8 pc=0x7fa6eb76f31b
runtime.call128(0x0, 0x7ffd4176b7d0, 0x7ffd4176b860, 0x48)
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:521 +0x54 fp=0xc000078ee0 sp=0xc000078e50 pc=0x7fa6eb2010a4
runtime.cgocallbackg1(0x0)
	/usr/lib/go-1.12/src/runtime/cgocall.go:314 +0x17b fp=0xc000078f58 sp=0xc000078ee0 pc=0x7fa6eb1ad7fb
runtime.cgocallbackg(0x0)
	/usr/lib/go-1.12/src/runtime/cgocall.go:191 +0xcb fp=0xc000078fc0 sp=0xc000078f58 pc=0x7fa6eb1ad5db
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:773 +0x9a fp=0xc000078fe0 sp=0xc000078fc0 pc=0x7fa6eb20259a
runtime.goexit()
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x7fa6eb202cf1
Aborted (core dumped)
```
Could I be doing something wrong?

**Comment by hunterInt** [comment]
storj-nodejs is unusable for me at this time. I've tried changing versions of GO, but that didn't solve the problem.

**Comment by kmozurkewich** [comment]
Hi,

The main inclusion is an artifact from our build process.  For now just follow the pattern in the HelloStorj.js file for usage.  Can you provide feedback on the following:

- What version of GO are you using? 

- How are you integrating/consuming libUplinkNode.js?

**Comment by hunterInt** [comment]
Hey @kmozurkewich thanks for your response.

- Go version: `go version go1.12.10 linux/amd64`

- I've been requiring the libUplinkNode.js file like so: `const storj = require(__dirname + '/node_modules/storj-nodejs/libUplinkNode.js');`  and I've tried this way too: `const storj = require('storj-nodejs');` both ways I get the same error.

This is the steps I took to get the error:

- `export PATH=$PATH:$GOPATH/bin`
- `go get storj.io/storj/lib/uplink`
- `npm install storj-nodejs`
- Copied `HelloStorj.js` to my project's root directory and into the `/node_modules/storj-nodejs/` folder (since I wasn't sure which the documentaion was referring to).
- `go build -o libuplinkc.so -buildmode=c-shared `
- Copied `libuplinkc.so` into my project's root directory and into the `/node_modules/storj-nodejs/` folder
- Then: 
```
const storj = require(rootDir + '/node_modules/storj-nodejs/libUplinkNode.js');
//OR
const storj = require('storj-nodejs');

await storj.new_uplink();
await storj.parse_api_key(storjApiKey)
```
Both ways I get this error:
```
unexpected fault address 0x800d
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x800d pc=0x7f72210a8f0e]

goroutine 17 [running, locked to thread]:
runtime.throw(0x7f722167911a, 0x5)
	/usr/lib/go-1.12/src/runtime/panic.go:617 +0x74 fp=0xc000078c90 sp=0xc000078c60 pc=0x7f72210d3a54
runtime.sigpanic()
	/usr/lib/go-1.12/src/runtime/signal_unix.go:397 +0x405 fp=0xc000078cc0 sp=0xc000078c90 pc=0x7f72210e80f5
indexbytebody(0x800d, 0xff3, 0x0, 0x70, 0xff3, 0x0, 0x800d, 0x800d, 0xff3, 0xc000078d68, ...)
	/usr/lib/go-1.12/src/internal/bytealg/indexbyte_amd64.s:124 +0xce fp=0xc000078cc8 sp=0xc000078cc0 pc=0x7f72210a8f0e
runtime.findnull(0x800d, 0x0)
	/usr/lib/go-1.12/src/runtime/string.go:448 +0x87 fp=0xc000078d20 sp=0xc000078cc8 pc=0x7f72210edb77
runtime.gostring(0x800d, 0x0, 0x0)
	/usr/lib/go-1.12/src/runtime/string.go:314 +0x31 fp=0xc000078d78 sp=0xc000078d20 pc=0x7f72210ed821
main._Cfunc_GoString(...)
	_cgo_gotypes.go:302
main.new_uplink(0x1, 0x0, 0x0, 0x0, 0x0, 0x800d, 0x1cd0240, 0x1ce71b0, 0x0)
	/home/hunter/go/src/storj.io/storj/lib/uplinkc/uplink.go:48 +0x132 fp=0xc000078df8 sp=0xc000078d78 pc=0x7f7221672e72
main._cgoexpwrap_7b24c107a305_new_uplink(0x1, 0x0, 0x0, 0x0, 0x0, 0x800d, 0x1cd0240, 0x1ce71b0, 0x1ce71b0)
	_cgo_gotypes.go:999 +0x5b fp=0xc000078e50 sp=0xc000078df8 pc=0x7f722166c31b
runtime.call128(0x0, 0x7fff467fed60, 0x7fff467fedf0, 0x48)
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:521 +0x54 fp=0xc000078ee0 sp=0xc000078e50 pc=0x7f72210fe0a4
runtime.cgocallbackg1(0x0)
	/usr/lib/go-1.12/src/runtime/cgocall.go:314 +0x17b fp=0xc000078f58 sp=0xc000078ee0 pc=0x7f72210aa7fb
runtime.cgocallbackg(0x0)
	/usr/lib/go-1.12/src/runtime/cgocall.go:191 +0xcb fp=0xc000078fc0 sp=0xc000078f58 pc=0x7f72210aa5db
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:773 +0x9a fp=0xc000078fe0 sp=0xc000078fc0 pc=0x7f72210ff59a
runtime.goexit()
	/usr/lib/go-1.12/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000078fe8 sp=0xc000078fe0 pc=0x7f72210ffcf1
Aborted (core dumped)
```

Any help would be much appreciated.

**Comment by kmozurkewich** [comment]
@hunterInt Another question - nodejs version you are using?

**Comment by hunterInt** [comment]
@kmozurkewich  NodeJS: `v10.15.2`

**Comment by varunpilankar** [comment]
Hey did anyone file a fix for this?

**Comment by kmozurkewich** [comment]
Not yet.  We have an update coming later this week.

**Comment by nileshbandekar** [comment]
@kmozurkewich 
I think, there is some problem on below line
main.new_uplink(0x1, 0x0, 0x0, 0x0, 0x0, 0x800d, 0x41b0830, 0x41b0810, 0x3)
	/home/nilesh/go/src/storj.io/storj/lib/uplinkc/uplink.go:48 +0x12e fp=0xc000066d88 sp=0xc000066d08 pc=0x7f8cfb03518e

we are not sending **user_agent in Volatile**  from libUplinkNode.js
![Screenshot from 2020-01-19 12-45-12](https://user-images.githubusercontent.com/44316189/72676652-bcda3800-3ab9-11ea-8da9-abe8db617ed4.png)

**UPDATE**
comment that line
and build with  "go build -o libuplinkc.so -buildmode=c-shared"

worked for me but not able to understand in case of python(https://pypi.org/project/storjPython/) why this error doesn't appear

**Comment by kmozurkewich** [comment]
@nileshbandekar @varunpilankar @hunterInt  - we just refactored the bindings.  Please check them out and let us know if you run into any issues or have suggestions.


Thanks!
