### ISSUE TITLE
libUplinkNode.js import in HelloStorj.js needs to be updated.

### ISSUE THREAD

**Issue by hanani8** [utropicmedia/storj-nodejs#10]
var storj = require("./libUplinkNode.js"), rather than var storj = require("./node_modules/storj-nodejs/libUplinkNode.js");

**Comment by kmozurkewich** [comment]
@hanani8  -  did you install from github or npm?

**Comment by hanani8** [comment]
> @hanani8 - did you install from github or npm?

github

**Comment by kmozurkewich** [comment]
@hanani8  - can you try the same with https://github.com/storj/uplink-nodejs ?  we are in the process of migrating repo locations as the code has recently gone to 1.0.

**Comment by hanani8** [comment]
Well, I did it from the github repo. Nonetheless, I manually changed it, and got it working.

I am new to the platform, so I have some questions. I tried asking them in the forum, but the response seems to be quite late, and tardigrade specific questions seem to be less in number in the forum, in general. 

My question is pretty simple, I would like to integrate this in my node.js application. Is the product, at this stage, suitable for that? Data confidentiality is of very high importance. So, that means, even me shouldn't be able to access user's documents. Can that be guaranteed?

thanks...

**Comment by kmozurkewich** [comment]
It is suitable for production integration.  The Tardigrade network (run by Storj Labs) has an enterprise SLA if you use their API keys.

For security, the cool thing about Storj is the data is encrypted before it leaves the client, so by the time it hits the network it's already encrypted and sharded.  Let us know if you have any questions - the Storj core team is really responsive.  The team here is responsible for some of the ecosystem tools and we can get you going with your node project.

**Comment by kmozurkewich** [comment]
closing.  please open a new issue if there is anything we can further assist with.
