### ISSUE TITLE
list_objectsc method either not working or incorrect documentaion

### ISSUE THREAD

**Issue by hunterInt** [utropicmedia/storj-nodejs#3]
Hello,

The documentation in this repo's README shows that `list_objectsc` takes one parameter:
```
inputs: valid BucketRef
```
However, the HelloStorj.js example file passes in two parameters: 
```
libUplink.list_objectsc(lO_OpenBucket.data,lO_listOptions);`
```
When I pass in just a single parameter (BucketRef) I get this error asking for 3 parameters:
![image](https://user-images.githubusercontent.com/14793417/73759148-7a497880-47a6-11ea-9d63-4270dfc91721.png)

Either way, both my code and the HelloStorj.js example file's `list_objectsc` doesn't return any items even though the sample.txt file was supposed to be uploaded correctly:
```
Opening  change-me-to-desired-bucket-name  Bucket...
change-me-to-desired-bucket-name  Bucket: OPENED!
./sample.txt  File: UPLOADED as  optionalpath/requiredfilename !
Data written on storj :  72
Commiting Object on storj...
Object Uploaded On storj

Listing objects within the Storj project's bucket... //<------- nothing listed ----------
Fetching object meta data from storj : 
Fetched Metadata of Object :  optionalpath/requiredfilename

Downloading  optionalpath/requiredfilename  Storj Object as  ./sample2.txt  file...
Total File Download from the storj :  72
Object Downloaded successfully
Creating Salted Key
Salted Key Received :  77

```
Example file reference: 
```
var listObject = libUplink.list_objectsc(lO_OpenBucket.data,lO_listOptions);

var objectsList = listObject.data;

console.log("\nListing objects within the Storj project's bucket...");

if (objectsList.length > 0) { //<--------------- This never gets a length of more than 0 -----------------
	console.log("S.No. \t Created On \t Object Path");
	console.log("===== \t ========== \t ===========");
}

var i=0;
for(object in objectsList.items){
	var num = "0" + (i + 1).toString();
	
	console.log(num.substr(-2), "  ", getDateTime(objectsList.items[object].created), "\t", objectsList.items[object].prefix);
	i++;
}
```
I don't believe this is a problem with a file not being uploaded, it could be, but since the example file shows that the sample.txt file was successfully downloaded I'm assuming it's an issue with the `list_objectsc` method. 

@kmozurkewich

**Comment by shivam201312** [comment]
@hunterInt  from above print statement it seems file/object is uploaded by name "optionalpath/requiredfilename !"

optionalpath -> it is a prefix
requiredfilename ! -> it is a objectname

for listing object we need to two parameters
1) BucketRef
2) ListOptions

In example file you need to change lO_listOptions.prefix

for example
if you will set prefix to blank string
lO_listOptions.prefix = "";

In listObject name of the object you will get : 
optionalpath
which is prefix of uploaded object .

if you want to display object and prefix inside optionalpath then you need to change list options prefix value 
lO_listOptions.prefix = "optionalpath/";

you will get **requiredfilename !** as output

I think changing listOptions.prefix will work for you .

What value are you using for lO_listOptions.prefix ?

**Comment by hunterInt** [comment]
@shivam201312 Ah ok I see. That makes more sense. I was confused by the example file, but changing the `lO_listOptions.prefix` worked for me. Thanks!
