### ISSUE TITLE
segment error: ecclient error: successful puts (45) less than success threshold (80)

### ISSUE THREAD

**Issue by hunterInt** [utropicmedia/storj-nodejs#4]
Hello,
Sorry to keep posting here, I just don't have any other way to find the answer (unless there is some documentation I don't know about?). 

When I try to commit an uploaded (`libUplink.upload_commitc(storjObj.uploaderObject.data);`) file that is 2MBs I'm getting this error:

```
		"segment error: ecclient error: successful puts (45) less than success threshold (80)
		storj.io/storj/uplink/ecclient.(*ecClient).Put:177
		storj.io/storj/uplink/storage/segments.(*segmentStore).Put:74
		storj.io/storj/uplink/storage/streams.(*streamStore).upload:262
		storj.io/storj/uplink/storage/streams.(*streamStore).Put:118
		storj.io/storj/uplink/storage/streams.(*shimStore).Put:50
		storj.io/storj/uplink/stream.NewUpload.func1:53
		golang.org/x/sync/errgroup.(*Group).Go.func1:57"
```

When I upload a file that is much smaller, 3.4KBs, it uploads without a problem. What does this error mean and how can I fix it? No errors came from `upload_writec` only `upload_commitc`. 

Thanks!

**Comment by kmozurkewich** [comment]
Hi,


That error indicates there is a connectiviry issue to the nodes.  Do you get it consistently(over 24-48 hours)?




-------- Original message --------

**Comment by hunterInt** [comment]
Hi @kmozurkewich 

I did get that error several times over 24-30 or so hours.

**Comment by kmozurkewich** [comment]
That error usually means there were comms issues when replicating and sharding the data.  Can you try over the weekend and let us know if the result changes?




-------- Original message --------

**Comment by kmozurkewich** [comment]
@hunterInt - any updates?  are you still getting the issue?

**Comment by hunterInt** [comment]
@kmozurkewich I am. I turned off my VPN and that seemed to prevent the error from happening as often. As of now, I am running this just locally, so being on a home network could perhaps be the reason the error still happens every so often, I guess.

**Comment by kmozurkewich** [comment]
Thanks for the feedback @hunterInt.  I'm going to close this one for now.  Feel free to open a new issue if you run into anything else we're happy to help!
