### ISSUE TITLE
 Reason: image not found Error On macOS 

### ISSUE THREAD

**Issue by CrackTheCode016** [utropicmedia/storj-nodejs#7]
NodeJS Version: 12.16.1
macOS Version: 10.14.6
Golang Version: go1.14.2 darwin/amd64

Hi all, I'm getting the following error when attempting to use `storj-nodejs` in my project: 
```
/Users/bader/Documents/Coding/storj-test/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/bader/Documents/Coding/storj-test/node_modules/storj-nodejs/build/Release/storjnodejs.node, 1): Library not loaded: libuplinkc.so
  Referenced from: /Users/bader/Documents/Coding/storj-test/node_modules/storj-nodejs/build/Release/storjnodejs.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/Users/bader/Documents/Coding/storj-test/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/bader/Documents/Coding/storj-test/node_modules/storj-nodejs/libUplinkNode.js:1:38)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
```

I've followed the installation instructions as per the repo - something interesting was this message after running: `go get storj.io/uplink-c`

```
# storj.io/common/rpc/rpcpool
../../../go/src/storj.io/common/rpc/rpcpool/pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:
	*Conn does not implement drpc.Conn (missing Closed method)
```

Any idea what could be happening here?  Thanks!

**Comment by kmozurkewich** [comment]
@CrackTheCode016  - this is an error in the build.  Basically to fix you need to clone the repo at https://github.com/storj/uplink-c into your $GOPATH/src directory and re-run the build.  

Prior to running the build can you clear-out the storj.io directory from your $GOPATH/src dir?  We've seen your specific error before when there is a version mismatch.

**Comment by CrackTheCode016** [comment]
Hi @kmozurkewich , thanks for answering,

I've cleared out everything Storj related from $GOPATH, cloned https://github.com/storj/uplink-c, and built it successfully with no errors.  Once I did that, I `rm -rf node_modules/`, `npm cache clean --force`, and reinstalled `storj-nodejs` where it also built with no errors (some warning about C++ string literal conversion, but nothing breaking). 

However, I'm still running into the same issue as before.

**Comment by CrackTheCode016** [comment]
Played with it some more, it appears I can run `HelloStorj.js` in the root of the repo (after cloning and building `storj-nodejs`), but anything trying to utilize `libUplinkNode.js` outside of the root of the project is a no go.  

Seems to maybe be a `node-gyp` build issue when it comes to macOS? Not familiar with node-gyp, so unsure.

**Comment by CrackTheCode016** [comment]
@kmozurkewich any comments or guidance on this?

**Comment by kmozurkewich** [comment]
@CrackTheCode016 - where is the libuplink.so in relation to the code you're using outside of the root?

**Comment by shivam201312** [comment]
@CrackTheCode016 Can you share output of the following command
1) Navigate to the node_module/storj_nodejs/build/Release/
```
tool -L storjnodejs.node
```

**Comment by CrackTheCode016** [comment]
fixed it! thanks @kmozurkewich for bringing it to my attention - I didn't know this was how it was supposed to be used :) 

> @CrackTheCode016 - where is the libuplink.so in relation to the code you're using outside of the root?

It was in `node_modules`, while my actual application is utilizing `storj-nodejs` via the node_module.  ` libuplink.so` was inside of `node_modules` - when placed inside of the root of the project, it works as intended.

**Comment by kmozurkewich** [comment]
@CrackTheCode016 - awesome!  We'll update the README and add your feedback.  The .js file is a wrapper to the native calls so you just need to make sure your path/env is configured to see the libUplinkNode.js file and the shared library that gets built during install.
